
GET {{host}}/channels?company_id={{company_id}}&workspace_id={{workspace_id}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0


> {%
    client.test("Request executed successfully", function() {
        client.global.set('channel_id', response.body[0]['id'])
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###


GET {{host}}/channels/members?company_id={{company_id}}&workspace_id={{workspace_id}}&channel_id={{channel_id}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###



POST {{host}}/channels
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "{{company_id}}",
  "workspace_id": "{{workspace_id}}",
  "visibility": "public",
  "name": "testChannel2",
  "members": ["291dae34-54ef-11eb-8031-0242ac120004"]
}


###


DELETE {{host}}/channels
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "{{company_id}}",
  "workspace_id": "{{workspace_id}}",
  "channel_id": "42427912-1de0-4678-8963-5bb16554f499"
}

###


POST {{host}}/channels
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "{{company_id}}",
  "visibility": "direct",
  "members": ["291dae34-54ef-11eb-8031-0242ac120004"]
}

###



POST {{host}}/channels/members
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "0e9337d6-54eb-11eb-9e45-0242ac120004",
  "workspace_id": "42b8bb1e-66b4-11eb-87df-0242ac120004",
  "channel_id": "61b73c44-7095-4678-8667-0308619d9bc4",
  "members": [
    "f3daa636-6548-11eb-a304-0242ac120004",
    "72ab8454-65bb-11eb-a040-0242ac120004"
  ]
}


###
