POST {{host}}/channels
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "{{company_id}}",
  "workspace_id": "{{workspace_id}}",
  "visibility": "public",
  "name": "testChannel",


###


DELETE {{host}}/channels
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "{{company_id}}",
  "workspace_id": "{{workspace_id}}",
  "channel_id": "42427912-1de0-4678-8963-5bb16554f499"
}

###


POST {{host}}/channels
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "{{company_id}}",
  "visibility": "direct",
  "members": ["291dae34-54ef-11eb-8031-0242ac120004"]
}

###



POST {{host}}/channels
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTIyODcyOTQsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE2MTIyODMwOTQsIm5iZiI6MTYxMjI4MzA5NCwic3ViIjoiMjkxZGFlMzQtNTRlZi0xMWViLTgwMzEtMDI0MmFjMTIwMDA0Iiwib3JnIjpbXX0.uK3XCTU4zQeCGlrUJg5LE5IvPJ3uznoVlvrbzGO5vrg
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "0e9337d6-54eb-11eb-9e45-0242ac120004",
  "workspace_id": "direct",
  "visibility": "direct",
  "default": true,
  "members": ["31a4a6a4-54f2-11eb-a382-0242ac120004", "291dae34-54ef-11eb-8031-0242ac120004"]
}

###
