POST {{host}}/channels
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "{{company_id}}",
  "workspace_id": "{{workspace_id}}",
  "visibility": "public",
  "name": "Coding"
}

###


POST {{host}}/channels
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0

{
  "company_id": "{{company_id}}",
  "visibility": "direct",
  "members": ["291dae34-54ef-11eb-8031-0242ac120004"]
}

###
