GET {{host}}/messages?company_id={{company_id}}&workspace_id={{workspace_id}}&channel_id={{channel_id}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###


GET {{host}}/messages/whatsnew?company_id={{company_id}}&workspace_id={{workspace_id}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###


GET {{host}}/messages?company_id={{company_id}}&workspace_id=direct&channel_id=88d04e29-67f2-4316-b209-fb76710331d5
Authorization: Bearer {{token}}
Content-Type: application/json
Accept-version: 2.0.0


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
