GET {{host}}/
Content-Type: application/json
Accept-version: 2.0.0

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
